#ifndef ASTEROIDS_EVENTS_H_
#define ASTEROIDS_EVENTS_H_

enum Event_t {
    EVT_SPACESHIP_SPAWN = 0,
    EVT_ASTEROID_SPAWN,
    EVT_SPACESHIP_THRUST,
    EVT_GAME_RESTART
};

#endif  // ASTEROIDS_EVENTS_H_